window._tx=function(d){d.lib=function(b){function k(){try{var a=new ActiveXObject("Msxml2.XMLHTTP")}catch(c){try{a=new ActiveXObject("Microsoft.XMLHTTP")}catch(C){a=!1}}a||"undefined"==typeof XMLHttpRequest||(a=new XMLHttpRequest);return a}b.txqpid=null;b.foadh=null;b.cdh=null;b.ddh=".hybrid.ai";b.aldhs=[".astraone.io",".adhello.pl",".rtbdro.id",".iclicks.io"];b.ppb=!1;var l=function(a){a.stringify=function(c){return window.JSON&&window.JSON.stringify?window.JSON.stringify(c):a.encode(c)};a.parse=
function(c){return window.JSON&&window.JSON.parse?window.JSON.parse(c):a.decode(c)};a.encode=function(a){switch(typeof a){case "string":return"'"+a+"'";case "number":return isFinite(a)?String(a):"null";case "boolean":case "null":return String(a);case "object":if(!a)return"null";var c=[];if("[object Array]"===Object.prototype.toString.apply(a)){for(var b=0;b<a.length;b++)c[b]=this.encode(a[b])||"null";return"["+c.join(",")+"]"}for(b in a)if(Object.prototype.hasOwnProperty.call(a,b)){var d=this.encode(a[b]);
d&&c.push("'"+b+"':"+d)}return"{"+c.join(",")+"}"}};a.decode=function(a){return null!==a&&"string"===typeof a&&/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[\da-fA-F]{4})/g,"@").replace(/"[^"\\\r\n]*"|true|false|null|-?(?:\d+\.|)\d+(?:[eE][+-]?\d+|)/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))?(new Function("return "+a))():null};return a}(d.JSON||{}),t=function(){var a={};try{location&&location.href&&4<location.href.length&&1E3>location.href.length&&(a.Url=location.href),document&&document.referrer&&
4<document.referrer.length&&1E3>document.referrer.length&&(a.Referrer=document.referrer),a.Language=navigator?navigator.language||navigator.browserLanguage:"",screen&&Number(screen.width)===screen.width&&0===screen.width%1&&Number(screen.height)===screen.height&&0===screen.height%1&&0<screen.width&&2147483647>screen.width&&0<screen.height&&2147483647>screen.height&&(a.ScreenWidth=screen.width,a.ScreenHeight=screen.height),a.TimezoneOffset=(new Date).getTimezoneOffset()/60}catch(c){}return a},u=function(a,
c,b){a.addEventListener?a.addEventListener(c,b,!1):a.attachEvent&&a.attachEvent("on"+c,b)},w=function(a,b){var c=document.createElement("script");c.type="text/javascript";c.async=b;c.src=a;(document.getElementsByTagName("head")[0]||document.getElementsByTagName("body")[0]).appendChild(c)},y=function(a){if(window.Image)var c=new Image;else document&&(c=document.createElement("img"),c.width=1,c.height=1);if(c)c.onload=c.onerror=function(){c.onload=null;c.onerror=null},c.src=a;else{var b=k();b&&(b.open("GET",
a,!0),b.send(null))}},z=function(){var a={apl:null,cs:"",pcs:[],vcs:[]},b=window.__tcfapi;if(!b)try{for(var d,e=window;e;){try{if(e.frames.__tcfapiLocator){d=e;break}}catch(g){}if(e===window.top)break;e=e.parent}if(d){var f={};b=function(a,b,c,e){var g=Math.random()+"";a={__tcfapiCall:{command:a,parameter:e,version:b,callId:g}};f[g]=c;d.postMessage(a,"*")};u(window,"message",function(a){a="string"===typeof a.data?l.parse(a.data):a.data;a.__tcfapiReturn&&(a=a.__tcfapiReturn,"function"===typeof f[a.callId]&&
(f[a.callId](a.returnValue,a.success),delete f[a.callId]))},!1)}}catch(g){}if(b)try{e=function(b,c){if(b){a.apl=a.apl||b.gdprApplies;a.cs=a.cs||b.tcString;if(b.purpose&&b.purpose.consents)for(var g in b.purpose.consents)b.purpose.consents[g]&&-1===a.pcs.indexOf(g)&&a.pcs.push(g);if(b.vendor&&b.vendor.consents)for(var e in b.vendor.consents)b.vendor.consents[e]&&-1===a.vcs.indexOf(e)&&a.vcs.push(e)}},b("getTCData",2,e),b("getTCData",1,e)}catch(g){}b=window.__cmp;if(!b)try{var h;for(e=window;!h;){try{e.frames.__cmpLocator&&
(h=e)}catch(g){}if(e===window.top)break;e=e.parent}if(h){var m={};b=function(a,b,c){var g=Math.random()+"";a={__cmpCall:{command:a,parameter:b,callId:g}};m[g]=c;h.postMessage(a,"*")};u(window,"message",function(a){a="string"===typeof a.data?l.parse(a.data):a.data;a.__cmpReturn&&(a=a.__cmpReturn,m[a.callId](a.returnValue,a.success),delete m[a.callId])},!1)}}catch(g){}if(b)try{e=function(b,c){if(b){a.apl=a.apl||b.gdprApplies;a.cs=a.cs||b.consentData||b.metadata||"";if(b.purposeConsents)for(var e in b.purposeConsents)b.purposeConsents[e]&&
-1===a.pcs.indexOf(e)&&a.pcs.push(e);if(b.vendorConsents)for(var d in b.vendorConsents)b.vendorConsents[d]&&-1===a.vcs.indexOf(d)&&a.vcs.push(d)}},b("getConsentData",null,e),b("getVendorConsents",null,e)}catch(g){}return a},n=function(a){return"foadh="+encodeURIComponent(a||"")},p=function(){var a=z();return"gapl="+(null!=a.apl?a.apl?"1":"0":"")+"&cs="+a.cs+"&pcs="+a.pcs.join("_")+"&vcs="+a.vcs.join("_")},x=function(){var a=document.getElementsByTagName("script");if(a)for(var c=0;c<a.length;c++)for(var d=
a[c].src,e=0;e<b.aldhs.length;e++){var f=b.aldhs[e];if(-1<d.indexOf(f)&&(-1<d.indexOf("txsp.js")||-1<d.indexOf("advertiser.js")))return f}return b.ddh},q=function(){return"https://dss"+(b.cdh||x())+"/"},r=function(a){b.ppb?window.setTimeout(function(){r(a)},1E3):(b.ppb=!0,y(a),window.setTimeout(function(){b.ppb=!1},1E3))},v=function(a,b,d,e,f,h,m,g,l){a="Pixel/Track2?pid="+(a||"")+"&bobid="+(b||"")+"&evt="+encodeURIComponent(d||"")+"&cost="+encodeURIComponent(e||"")+"&text="+encodeURIComponent(f||
"")+"&ltm="+(m||!1)+"&cnt="+(h||"")+"&url="+encodeURIComponent(g.Url||"")+"&rf="+encodeURIComponent(g.Referrer||"")+"&lng="+(g.Language||"")+"&tz="+(g.TimezoneOffset||"")+"&sw="+(g.ScreenWidth||"")+"&sh="+(g.ScreenHeight||"")+"&"+n(l)+"&"+p()+"&r=";r(q()+a)},A=function(a,b,d,e,f,h){a="Pixel/DynamicTrack?pid="+(a||"")+"&bobid="+(b||"")+"&evt="+encodeURIComponent(d||"")+"&cnt="+encodeURIComponent(e||"")+"&url="+encodeURIComponent(f.Url||"")+"&rf="+encodeURIComponent(f.Referrer||"")+"&lng="+(f.Language||
"")+"&tz="+(f.TimezoneOffset||"")+"&sw="+(f.ScreenWidth||"")+"&sh="+(f.ScreenHeight||"")+"&"+n(h)+"&"+p()+"&r=";r(q()+a)},B=function(a,b,d,e,f,h,m){a="Pixel/Identify2?pid="+(a||"")+"&bobid="+(b||"")+"&cstid="+(d||"")+"&icnt="+(e||"")+"&ucnt="+(f||"")+"&url="+encodeURIComponent(h.Url||"")+"&rf="+encodeURIComponent(h.Referrer||"")+"&lng="+(h.Language||"")+"&tz="+(h.TimezoneOffset||"")+"&sw="+(h.ScreenWidth||"")+"&sh="+(h.ScreenHeight||"")+"&"+n(m)+"&"+p()+"&r=";r(q()+a)};b.txqhnd=function(a){if(a&&
"string"===typeof a[0]){var c=a[0].toLowerCase();if("createpixel"===c)"string"==typeof a[1]&&(b.txqpid=a[1],a[2]&&(b.foadh=1),window.setTimeout(function(){var a=n(b.foadh),c=p();w("https://emd.hybrid.ai/plgt.js?fbpid="+b.txqpid+"&"+a+"&"+c,!0)},2E3));else if("track"===c){if("string"===typeof a[1]){var k=a[1],e=null;try{a[2]&&(e=encodeURIComponent(l.stringify(a[2])))}catch(m){}var f=t();"pageview"===k.toLowerCase()?(v(b.txqpid,d.HybridAiBobId,k,null,null,e,!1,f,b.foadh),a=n(b.foadh),c=p(),w(q()+"Pixel/TrackTp?pid="+
(b.txqpid||"")+"&"+a+"&"+c,!0),window.setTimeout(function(){v(b.txqpid,d.HybridAiBobId,k,null,null,e,!0,f,b.foadh)},15E3)):v(b.txqpid,d.HybridAiBobId,k,a[3],a[4],e,!1,f,b.foadh)}}else if("track_d"===c){if("string"===typeof a[1]&&"string"===typeof a[2]){c=a[1];a=a[2];var h=t();A(b.txqpid,d.HybridAiBobId,c,a,h,b.foadh)}}else if("identify"===c&&"string"===typeof a[1]){h=c=null;try{a[2]&&(c=encodeURIComponent(l.stringify(a[2]))),a[3]&&(h=encodeURIComponent(l.stringify(a[3])))}catch(m){}B(b.txqpid,d.HybridAiBobId,
a[1],c,h,t(),b.foadh)}}};b.txq=function(a){this.push(a)};b.txq.prototype.push=function(a){b.txqhnd(a)};b.txqi=function(){window._txq=window._txq||[];if(window._txq)for(var a in window._txq)window._txq.hasOwnProperty(a)&&b.txqhnd(window._txq[a]);"complete"==document.readyState?window._txq=new b.txq(window._txq):u(document,"readystatechange",function(){window._txq=new b.txq(window._txq)});b.cdh=x()};return b}(d.lib||{});if(d.HybridAiBobId||"function"!=typeof Promise)d.lib.txqi();else{var k=document.createElement("script");
k.src="https://fp.hybrid.ai/bobid.js";k.async=!0;k.onload=function(){window.HybridBobId.get().then(function(b){b&&b.success&&(d.HybridAiBobId=b.id);d.lib.txqi()})};k.onerror=function(){d.lib.txqi()};(document.getElementsByTagName("head")[0]||document.getElementsByTagName("body")[0]).appendChild(k)}d.sendPixel=function(b){d.lib.txqhnd(["createPixel",b]);d.lib.txqhnd(["track","PageView"])};d.sendEvent=function(b,k){d.lib.txqhnd(["createPixel",b]);d.lib.txqhnd(["track",k])};d.sendProductView=function(b,
k,l){d.lib.txqhnd(["createPixel",b]);d.lib.txqhnd(["track","ViewContent",{content_type:"product",content_ids:[l]}])};d.MarkVisitor=function(){};d.sendAudience=function(){};d.sendAudienceTags=function(){};return d}(window._tx||{});
